# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Himemori Luna
  - trigger: ":lunabye"
    replace: ":_おつつ::_ルーナ:"
  - trigger: ":lunachr"
    replace: ":_サイリウムム::_パパんなああ::_サイリウム:"
  - trigger: ":lunachu"
    replace: ":_ちゅー::_ちゅー::_ちゅー:"
  - trigger: ":lunacij"
    replace: ":_CIJ::_CIJ::_CIJ:"
  - trigger: ":lunaerai"
    replace: ":_えらい::_えらい::_えらい:"
  - trigger: ":lunagg"
    replace: ":_えらい::_えらい::_えらい:"
  - trigger: ":lunahi"
    replace: ":_んんん::_ななな::_あああ::_あああ::_あああ::_あああ::_あああ::_あああ::_あああ:"
  - trigger: ":lunakw"
    replace: ":_かわいい::_かわいい::_かわいい:"
  - trigger: ":lunalol"
    replace: ":_くさくさ:"
  - trigger: ":lunamad"
    replace: ":_ぷっぷ::_ぷっぷ::_ぷっぷ:"
  - trigger: ":lunamwah"
    replace: ":_パパちゅー::_パパちゅー::_パパちゅー:"
  - trigger: ":lunananora"
    replace: ":_ななな::_ののの::_ららら:"
  - trigger: ":lunanay"
    replace: ":_ルーナ::_わからない::_ののの::_ららら:"
  - trigger: ":lunannaa"
    replace: ":_んなああ:"
  - trigger: ":lunaoru"
    replace: ":_おるる::_よよよ:"
  - trigger: ":lunaprr"
    replace: ":_prr::_prr::_prr:"
  - trigger: ":lunatako"
    replace: ":_タコしゃん::_タコしゃん::_タコしゃん:"
  - trigger: ":lunathx"
    replace: "ありが:_ちゅー:"
  - trigger: ":lunawlb"
    replace: ":_わらびー::_わらびー::_わらびー:"
  - trigger: ":lunayay"
    replace: ":_わかる:"
  - trigger: ":luna!!"
    replace: ":_パパんなああ::_パパんなああ::_パパんなああ:"
  - trigger: ":luna.."
    replace: ":_マリルーナ::_マリルーナ::_マリルーナ:"
  # Momosuzu Nene
  - trigger: ":nenebotan"
    replace: ":_ねねのかお::_ししろのかお:"
  - trigger: ":nenebye"
    replace: "また:_ねねねね::_ねねねね::_のばしぼう:"
  - trigger: ":nenechr"
    replace: ":_ペンライト::_ねねのかお::_ペンライト:"
  - trigger: ":neneclap"
    replace: ":_hakusyu::_hakusyu::_hakusyu::_hakusyu::_hakusyu::_hakusyu::_hakusyu:"
  - trigger: ":nenedoya"
    replace: ":_NENE1::_NENE1::_NENE1:"
  - trigger: ":nenegen5"
    replace: ":_ねねのかお::_おまるのかお::_らみぃのかお::_ししろのかお:"
  - trigger: ":nenegod"
    replace: ":_nenechigod::_ねねのかお::_nenechigod:"
  - trigger: ":nenehaan"
    replace: ":_はぁん:"
  - trigger: ":nenehi"
    replace: "こん:_ねねねね::_ねねねね::_のばしぼう:"
  - trigger: ":nenemad"
    replace: ":_NENE3::_NENE3::_NENE3:"
  - trigger: ":nenemizu"
    replace: ":_みずみず::_みずみず::_みずみず:"
  - trigger: ":nenelamy"
    replace: ":_ねねのかお::_らみぃのかお:"
  - trigger: ":nenepol"
    replace: ":_ねねのかお::_おまるのかお:"
  - trigger: ":nenepsk"
    replace: ":_ぷんぷん::_すこすこ::_ぷんぷん::_すこすこ:"
  - trigger: ":nenesad"
    replace: ":_NENE2::_NENE2::_NENE2:"
  - trigger: ":nenesmsy"
    replace: "それマジすごいやん！"
  - trigger: ":nenettk"
    replace: ":_hakusyu::_hakusyu::_hakusyu:"
  - trigger: ":nenewait"
    replace: "待機:_ねねのかお:"
  - trigger: ":nenewin"
    replace: "勝ったなガハハ"
  - trigger: ":nene!!"
    replace: ":_NENE4::_NENE4::_NENE4:"
  - trigger: ":nene!?"
    replace: ":_NENE5::_NENE5::_NENE5:"
  - trigger: ":nene><"
    replace: ":_NENE6::_NENE6::_NENE6:"
  - trigger: ":nene7chr"
    replace: ":_ペンライト::_NENE7::_ペンライト:"
  - trigger: ":nene7god"
    replace: ":_nenechigod::_NENE7::_nenechigod:"
  - trigger: ":nene7wait"
    replace: "待機:_NENE7:"
  - trigger: ":nene7!!"
    replace: ":_NENE7::_NENE7::_NENE7:"
